spring.application.name=innovacion
spring.config.import=optional:file:.env[.properties]
spring.profiles.default=local
server.port=8080

app.security.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:480}
